version:  '3'
services:
    postgres:
        container_name:  postgres
        image:  postgres:latest
        ports:
            -  "5432:5432"
        volumes:
        - ./data:/postgres/
        environment:
            POSTGRES_USER:  luna
            POSTGRES_PASSWORD:  a
            POSTGRES_DB:  luna
    api:
      container_name: luna-api
      build: .
      ports:
        - "80:80"
      volumes:
        - ./data:/luna/
      links:
        - postgres
      environment:
        - WEBSERVER_PORT=80
        - WEBSERVER_ADRESS=0.0.0.0
        - DATABASE_URL=postgresql://luna:a@postgres:5432/luna?schema=public